#!/bin/sh
set -e
$1 -t 'A  =  A'
$1 -t '~F  =  T'
$1 -t '~T  =  F'
$1 -t 'A \/ A  =  A'
$1 -t 'A /\ A  =  A'
$1 -t 'A /\ B  =  B /\ A'
$1 -t 'A \/ B  =  B \/ A'
$1 -t 'A /\ (B /\ C)  =  (A /\ B) /\ C'
$1 -t 'A \/ (B \/ C)  =  (A \/ B) \/ C'
$1 -t 'A /\ (B \/ C)  =  A /\ B \/ A /\ C'
$1 -t 'A \/ (B /\ C)  =  (A \/ B) /\ (A \/ C)'
$1 -t '~(A /\ B)  =  ~A \/ ~B'
$1 -t '~(A \/ B)  =  ~A /\ ~B'
$1 -t '~~A  =  A'
$1 -t 'A /\ ~A  =  F'
$1 -t 'A \/ ~A  =  T'
$1 -t 'A /\ T  =  A'
$1 -t 'A \/ F  =  A '
$1 -t 'A /\ F  =  F'
$1 -t 'A \/ T  =  T'
$1 -t 'A -> B  =  ~A \/ B'
$1 -t '(A <-> B)  = (A -> B) /\ (B -> A)'
$1 -t 'A @ B  =  A /\ ~B \/ ~A /\ B'
$1 -t 'A @ B  =  ~(A  <->  B)'
$1 -t '(A <-> (B <-> C))  =  ((A <-> B) <-> C)'
$1 -t 'T -> F  =  F'
$1 -t 'A /\ B \/ C = (A /\ B) \/ C'
$1 -t 'A \/ B /\ C = A \/ (B /\ C)'
$1 -t 'A -> B -> C  =  (A -> B) -> C'
$1 -t 'a.b  =  a /\ b'
$1 -t 'a+b  =  a \/ b'
$1 -t 'a>b  =  a -> b'
$1 -t '(a=b)  =  (a <-> b)'
$1 -t '0  =  F'
$1 -t '1  =  T'
