.\"
.\"     Title: ca
.\"    Author: Sian Mountbatten <poenikatu@fastmail.co.uk>
.\" Generator: The author
.\"      Date: 12\ \&Sept\ \&2012
.\"    Manual: Algol 68
.\"    Source: algol68toc 1.15
.\"  Language: English
.\"
.TH "CA" "1" "2012-09-12" "algol68toc 1.14" "Algol 68 Programmers' Manual"
.Dd Sept 12, 2012
.Dt CA 1
.Os "Debian GNU/Linux"
.
.Sn NAME
.
.Nm ca
.Nd compile an Algol 68 module
.
.
.Sh SYNOPSIS
.
.Nm
.Op Fl c
.Op Fl C Ar c-flag
.Op Fl d Ar m-files-dir
.Op Fl g
.Op Fl h | Fl \-help
.Op Fl I Ar inc-dir
.Op Fl L Ar link-dir
.Op Fl l Ar link-lib
.Op Fl M Ar lib-dir
.Op Fl m Ar mod-lib
.Op Fl u Ar uname
.Op Fl w Ar web68-dir
.Ar module-path Ns Op \&.a68 Ns | Ns \&.w68
.
.
.Sh DESCRIPTION
.
.Nm
will convert a source module written in Algol 68 or Web 68 into an
object module. If it is a program,
.Nm
will link it to form a binary program in the directory specified by
.Ar module-path
\&. Otherwise, it will store the object module in a static library
specified in a
.Fl m
argument which should be preceded by a
.Fl M
argument giving its directory. If the
.Fl M
option is not used, the default directory for the static library
file will be used (it is
.Pa ~/lib
\&. The module will include debugging symbols if the option
.Fl g
is used.
.Nm
is intended to replace the module manager
.Ql mm
usually supplied with the
.Xr a68toc 1
translator, and the
.Xr make 1
command. Note that generally the argument of an option should be separated from the
option by a space.
.
.Pp
.Nm
will run
.Xr tang 1
if the file extension is
.Pa .w68
\&. If the filename has no extension,
.Ql .a68
is presumed.
.
.
.Sh OPTIONS
.
.
The following options are available:-
.Bl -tag -width Ds
.
.
.It Fl c
Remove run-time checks from the compiled program (not recommended).
.
.
.It Fl C
Specify a flag for the C compiler. This option may be repeated.
.
.
.It Fl d Ar m-files-dir
Add
.Ar m-files-dir
to the list of directories containing \&.m files produced by
.Xr a68toc 1
for precompiled modules. The default value is
.Bl -tag -width 10n -offset indent
.It Pa /usr/share/algol68/
\&.
.El
.Lp
The last directory added will be searched first. This option may be
repeated.
.
.
.It Fl g
Add debugging symbols to your program. Only the programs
.Xr a68toc 1
and
.Xr gcc 1
are affected by the
.Fl g
flag.
.
.It Fl h | Fl \-\-help
Displays a terse help message together with the defaults of arguments.
.
.
.It Fl I Ar inc-dir
Add
.Ar inc-dir
to the list of directories which
.Xr gcc 1
should be searched for included C files. The default value is
.Bl -tag -width 10n -offset indent
.It Li -I /usr/include/algol68 -I /usr/include
.El
.Lp
This option may be repeated.
.
.
.It Fl L Ar link-dir
Adds
.Ar link-dir
to the list of directories in which
.Xr gcc 1
will search for libraries for linking. It should be followed by
.Fl l Ar link-lib
arguments indicating the libraries to be searched. The default is
.Bl -tag -width 10n -offset indent
.It Li -L /usr/lib -L ${HOME}/lib
.El
.Lp
This option may be repeated.
.
.
.It Fl l Ar link-lib
Adds
.Ar link-lib
to the list of libraries which
.Xr gcc 1
will search for precompiled routines for linking. It should be preceded by
a
.Fl L Ar link-dir
option giving the directory to search for the library unless it can
be found in the list of libraries already defined (or by default).
The following libraries are searched last in the linking process:-
.Bl -tag -width 10n -offset indent
.It Li -la68s -la68 -lm -lc
.El
.Lp
This option may be repeated.
.
.
.It Fl M Ar lib-dir
Specifies the directory which contains static libraries of
pre-compiled modules.
.Nm
presumes that the
.Li .m
file produced by
.Xr a68toc 1
will be stored in the sub-directory
.Li m
of
.Li lib-dir
\&.
Usually, these libraries will contain modules
compiled by
.Xr a68toc 1
\&.
.Nm
presumes that the .m file produced by
.Xr a68toc 1
from a declarations module will be moved to the sub-directory
.Ql m
in the directory specified by this parameter. The default
.Fl M
directory is
.Pa ~/lib
\&. The argument should not be repeated.
.
.
.It Fl m Ar mod-lib
Specifies a static library of pre-compiled modules. When compiling a
DECS module, if the library does not exist, it will be
created. Both the lib in the name and the suffix of .a may be omitted.
.
.
.It Fl u Ar uname
Specifies the
.Ar uname
command for
.Xr a68toc 1 .
The default is
.Ql seedfile .
See
.Xr a68toc 1
for further details.
.
.
.It Fl w Ar web68-dir
Specifies a directory to be added to the list of directories in which
.Xr tang 1
should look for Web 68 include files. The default value is
.Bl -tag -width 10n -offset indent
.It Pa ${HOME}/lib
.El
The option can be repeated.
.
.El
.
.Sh FILES
.
None.
.
.
.Sh ENVIRONMENT
.
None.
.
.Sh EXAMPLES
.
.Bl -tag -width Ds
.
.It Ar "ca prog"
This command will translate the source
.Ar prog.a68
into C, compile it with
.Xr gcc 1
and then link it to produce the executable
.Pa prog
in the current directory. The object file
.Li prog.o
will be linked with the standard Algol 68 libraries.
.
.
.It Ar "ca -d ~/lib/m -l forms -w . prog.w68"
This command will run
.Xr tang 1 ,
then
.Xr a68toc 1 ,
then
.Xr gcc 1
and will then link the resulting
.Pa prog.o
file with the Xforms libraries. Included Web 68 files will be searched
for in the current working directory and directory
.Pa ~/lib
\&. The directory
.Pa ~/lib/m
will be searched for .m files of precompiled modules.
.
.
.It Ar "ca -d . -M ~/lib -m mod decs.a68"
The declaration module
.Ar decs.a68
will be translated to C, compiled to object form and then stored in
.Pa libmod.a
in directory
.Pa ~/lib
\&. The
.Li .m
file will be stored in
.Pa ~/lib/m
\&.m files from precompiled modules will be looked for in the current
working directory.
.
.El
.
.
.Sh SEE ALSO
.Xr a68toc 1
.Xr gcc 1
.Xr tang 1
.
.
.Sh COPYRIGHT
Copyright (C) 2012 Sian Mountbatten and available under the GNU
Public Licence version 2 or any later version.
.
.
.Sh AUTHOR
Sian Mountbatten
